name: assets_generator
description: The flutter tool to generate assetsâ€˜s configs(yaml) and consts automatically for single project and multiple modules.
version: 3.0.1
homepage: https://github.com/fluttercandies/assets_generator

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.2.0
  build_runner_core: ^7.1.0
  dart_style: ^2.0.3
  io: ^1.0.3
  meta: ^1.7.0
  path: ^1.8.0
  source_span: ^1.8.1
  yaml: ^3.1.0

dev_dependencies:
  pedantic: ^1.11.1

executables:
  agen: assets_generator


# pub global activate --source path ./
# pub global activate assets_generator