name: assets_generator
description: The flutter tool to generate assetsâ€˜s configs(yaml) and consts automatically for single project and multiple modules.
version: 4.0.4
homepage: https://github.com/fluttercandies/assets_generator

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.2.0
  build_runner_core: ">=7.1.0 <10.0.0"
  dart_style: ">=2.3.8 <4.0.0"
  io: ^1.0.3
  meta: ^1.7.0
  mime: ">=1.0.2 <3.0.0"
  source_span: ^1.8.1
  path: ^1.8.0
  pub_semver: ^2.2.0
  yaml: ^3.1.0

dev_dependencies:
  lints: any

executables:
  agen: assets_generator
# dart pub global activate --source path ./
# dart pub global activate assets_generator
